services:
  prunemate:
    build: .  # Build locally instead of using pre-built image
    container_name: prunemate
    #ports:
    #  - "7676:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log
      - ./config:/config
    environment:
      - PRUNEMATE_TZ=America/Guayaquil
      - PRUNEMATE_TIME_24H=true #false for 12-Hour format (AM/PM)
      - PRUNEMATE_AUTH_USER=${PRUNEMATE_AUTH_USER}
      - PRUNEMATE_AUTH_PASSWORD_HASH=${PRUNEMATE_AUTH_PASSWORD_HASH}
    #restart: unless-stopped
